name: procon_golang_test
on: [push]

jobs:
  build:
    name: all
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v5
      - name: set up
        uses: actions/setup-go@v5
        with:
          go-versio-file: ./go.mod
      - name: template-test
        run: go test ./library/template/... -v
      - name: cmd-test
        run: go test ./cmd/... -v
